## Numpy Random

In [1]:
import numpy as np

In [2]:
np.random.seed(17)

In [3]:
W1 = np.random.rand(64, 128) * 2 - 1
W2 = np.random.rand(128, 10) * 2 - 1

In [4]:
# выведем размерности матриц весов
W1.shape, W2.shape

((64, 128), (128, 10))

#### Загрузим данные

In [5]:
from sklearn.datasets import load_digits

In [6]:
data = load_digits(return_X_y=True)

In [7]:
# распарсим данные, тк data = (картинки, название класса)
X, y_raw = data

# выведем размерности
X.shape, y_raw.shape 

((1797, 64), (1797,))

In [8]:
y_raw[:5]

array([0, 1, 2, 3, 4])

In [9]:
# превратим вектор y, хранящий названия классов
# в матрицу y, хранящую распределение вероятностей классов
y = np.zeros((1797, 10))
y[range(0, 1797), y_raw] = 1

# выведем размерности
X.shape, y.shape 

((1797, 64), (1797, 10))

#### Функция активации 

In [10]:
def ReLU(vector):
    v_copy = vector.copy()
    
    mask = v_copy < 0
    v_copy[mask] = 0
    
    return v_copy

In [11]:
tmp = np.array([-1, -3, 0, 4, 5, 9])

ReLU(tmp)

array([0, 0, 0, 4, 5, 9])

#### Forward pass (прогоним нашу картинку через нейросеть)

In [12]:
# forward pass
H = ReLU( X[0].dot(W1) )
S = H.dot(W2) 

In [13]:
S.shape

(10,)

#### Softmax

In [14]:
def softmax(s):
    e = np.exp(s)
    summ = np.sum(e)
    return e / summ

In [15]:
p = softmax(S).astype(np.float16)

p 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float16)

In [16]:
y[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Loss function

In [17]:
def loss(predict, true):
    return np.sum((predict - true)**2)

In [18]:
# посчитаем насколько ошиблась нейросеть на первой картинке (максимальное значение = 2)
loss(p, y[0])

2.0