# Numpy

Numpy [numerical python] - это модуль языка питон. То есть это файл с кодом на языке Python. Этот файл реализовали нашими коллеги-программы, которые решили поделиться своими наработками. Блягодаря этому, мы можем очень удобным образом работать с векторами и матрицами, умножать их друг на друга и многое другое.
<br><br>
Чтобы импортировать Numpy-модуль в наш код, следует исполнить следующую команду:

In [1]:
import numpy as np

Строка **import numpy** импортирует модуль, доступ к функциям которого мы будем иметь через слово **np** (as - переводится "как", то есть мы будем обращаться к модулю numpy через сокращение np). Например, в Numpy-модуле реализованы функции max(), и min(). Но чтобы вызвать именно их, а не те, что уже реализованы в Python, следует исполнить: np.max(), np.min(). То есть через сокращение модуля и точку мы можем вызывать реализованные в нем функции.

#### Numpy array

In [2]:
# чтобы создать numpy вектор, следует воспользоваться функцией np.array()
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([-1,0,1,3,-1,9,11,3,1])

In [3]:
# скалярное произведение
# способ 1:
print(a.dot(b))

# способ 2:
print(np.dot(a, b))

173
173


In [4]:
# умножение на скаляр
a * 7

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [5]:
# распечатаем массив
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# индексация по массиву
# можем выводить "срезы" вектора
# [с какого : по какой (не включительно) : с каким шагом]
a[1:9:2]

array([2, 4, 6, 8])

#### Матрицы

In [7]:
# numpy матрицы
# можем также создавать numpy матрицы, только 
# потребуется передать двумерный массив в функцию np.array()
m1 = np.array([[ 1, 2, 3, 4], 
               [-1, 5, 6, 8], 
               [ 5, 2, 3, 7], 
               [ 0, 5,-1, 7]])

# numpy вектор (массив)
v1 = np.array([-1, 4, 3, 0])

In [8]:
# умножим матрицу на вектор
m1.dot(v1)

array([16, 39, 12, 17])

In [9]:
# сложная индексация по матрице
# до запятой указываем какие вырезать столбцы,
# после запятой строки 
# [от:до(не включительно), от:до(не включительно)]
m1[1:3, 1:3]

array([[5, 6],
       [2, 3]])

In [10]:
# транспонирование матрицы (строки превратить в столбцы)
m1.T

array([[ 1, -1,  5,  0],
       [ 2,  5,  2,  5],
       [ 3,  6,  3, -1],
       [ 4,  8,  7,  7]])

In [11]:
# узнать размерность матрицы (строки, столбцы)
# можно при помощи свойства .shape
# круглые скобки не нужны, так как это свойство! а не метод (функция)!
m1.shape

(4, 4)

In [12]:
# можно изменить размерность матрицы, главное указать такую,
# чтобы хватило элементов в матрице.
# например, если в матрице 20 элементов, то не получится
# изменить размерность на 5 строк и 6 столбцов, так как 
# для такой матрицы уже понадобится 5*6=30 элементов
m1.reshape((8,2))

array([[ 1,  2],
       [ 3,  4],
       [-1,  5],
       [ 6,  8],
       [ 5,  2],
       [ 3,  7],
       [ 0,  5],
       [-1,  7]])